services:
  pipes-filters:
    build:
      context: .
    ports:
      - "8000:8000"
    command: python /src/main.py
    env_file: env
    networks:
      - indocker2

networks:
  indocker2:
    driver: bridge
